### ISSUE TITLE
[Q] kubernetesCRD insted of kubernetesIngress

### ISSUE THREAD

**Issue by FL3SH** [mmatur/traefik-cert-manager#10]
Hi, it is possible to use kubernetesCRD for cert-manager instead of kubernetesIngress?

**Comment by mmatur** [comment]
Hi @FL3SH,

Unfortunately it is not possible, As you can read in the cert manager [documentation](https://cert-manager.io/docs/configuration/acme/http01/#configuring-http01-ingress-provider). Only ingress object can bu use to solve http challenge. 

I am closing this issue because you question is answered

**Comment by FL3SH** [comment]
Thank you
